// Bursa / Yıldırım İlçesi Mahalleleri (71 Mahalle)
// Kaynak: https://www.yildirim.gov.tr/mahalli-idareler
export const YILDIRIM_MAHALLELERI = [
  '152 Evler',
  '75. Yıl',
  'Akçağlayan',
  'Anadolu',
  'Arabayatağı',
  'Bağlaraltı',
  'Balaban',
  'Baruthane',
  'Beyazıt',
  'Cumalıkızık',
  'Çelebi Mehmet',
  'Çınarönü',
  'Davutdede',
  'Davutkadı',
  'Değirmenlikızık',
  'Değirmenönü',
  'Demetevler',
  'Duaçınarı',
  'Eğitim',
  'Emirsultan',
  'Erikli',
  'Ertuğrulgazi',
  'Esenevler',
  'Fidyekızık',
  'Güllük',
  'Hacıseyfettin',
  'Hacivat',
  'Hamamlıkızık',
  'Hocataşkın',
  'İsabey',
  'Kaplıkaya',
  'Karaağaç',
  'Karamazak',
  'Karapınar',
  'Kazım Karabekir',
  'Kurtoğlu',
  'Maltepe',
  'Mehmet Akif Ersoy',
  'Mevlana',
  'Meydancık',
  'Millet',
  'Mimar Sinan',
  'Mollaarap',
  'Musababa',
  'Namazgah',
  'Ortabağlar',
  'Piremir',
  'Sakarya',
  'Samanlı',
  'Selçukbey',
  'Selimzade',
  'Sıracevizler',
  'Sinandede',
  'Siteler',
  'Şirinevler',
  'Şükraniye',
  'Teferrüç',
  'Ulus',
  'Umurbey',
  'Vakıf',
  'Vatan',
  'Yavuzselim',
  'Yediselviler',
  'Yenimahalle',
  'Yeşil',
  'Yeşilyayla',
  'Yıldırım',
  'Yiğitler',
  'Yunusemre',
  'Zeyniler',
  'Zümrütevler',
].sort((a, b) => a.localeCompare(b, 'tr'));

// Mahalle sayısı
export const MAHALLE_SAYISI = YILDIRIM_MAHALLELERI.length; // 71
