-- =============================================
-- TÜRKÇE KARAKTER DESTEĞİ İÇİN COLLATION DÜZELTMESİ
-- =============================================

USE IsYonetimDB;
GO

-- Projects tablosundaki text kolonları Turkish collation ile güncelle
ALTER TABLE Projects ALTER COLUMN Title NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Projects ALTER COLUMN Description NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Projects ALTER COLUMN Status NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Projects ALTER COLUMN Priority NVARCHAR(50) COLLATE Turkish_CI_AS;
GO

-- Agendas tablosu
ALTER TABLE Agendas ALTER COLUMN Title NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Agendas ALTER COLUMN Description NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Agendas ALTER COLUMN Status NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Agendas ALTER COLUMN Priority NVARCHAR(50) COLLATE Turkish_CI_AS;
GO

-- Pendings tablosu
ALTER TABLE Pendings ALTER COLUMN Title NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Pendings ALTER COLUMN Description NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Pendings ALTER COLUMN Type NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Pendings ALTER COLUMN Status NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Pendings ALTER COLUMN Priority NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Pendings ALTER COLUMN RequesterName NVARCHAR(100) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Pendings ALTER COLUMN Location NVARCHAR(255) COLLATE Turkish_CI_AS NULL;
GO

-- Schedules tablosu
ALTER TABLE Schedules ALTER COLUMN Title NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Schedules ALTER COLUMN Description NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Schedules ALTER COLUMN Type NVARCHAR(50) COLLATE Turkish_CI_AS;
ALTER TABLE Schedules ALTER COLUMN Location NVARCHAR(255) COLLATE Turkish_CI_AS NULL;
GO

-- Cenazes tablosu
ALTER TABLE Cenazes ALTER COLUMN VefatEden NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Cenazes ALTER COLUMN NamazVakti NVARCHAR(50) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Cenazes ALTER COLUMN Mahalle NVARCHAR(100) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Cenazes ALTER COLUMN Notlar NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Cenazes ALTER COLUMN YakinAdi NVARCHAR(100) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Cenazes ALTER COLUMN Yakinlik NVARCHAR(50) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Cenazes ALTER COLUMN GorevliAdi NVARCHAR(100) COLLATE Turkish_CI_AS NULL;
GO

-- Users tablosu
ALTER TABLE Users ALTER COLUMN Name NVARCHAR(100) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Users ALTER COLUMN Role NVARCHAR(50) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Users ALTER COLUMN Mahalle NVARCHAR(100) COLLATE Turkish_CI_AS NULL;
GO

-- Notifications tablosu
ALTER TABLE Notifications ALTER COLUMN Title NVARCHAR(255) COLLATE Turkish_CI_AS NOT NULL;
ALTER TABLE Notifications ALTER COLUMN Message NVARCHAR(MAX) COLLATE Turkish_CI_AS NULL;
ALTER TABLE Notifications ALTER COLUMN Type NVARCHAR(50) COLLATE Turkish_CI_AS;
GO

PRINT 'Tüm tablolar Turkish_CI_AS collation ile güncellendi!';
GO
